#!/usr/bin/env python3
"""Pre-render half-width katakana (U+FF66..U+FF9D) to 4x8 bitmaps.

Writes src/kana_glyphs.nim. Glyphs come from GNU Unifont (8x16, dual-licensed
GPL-2.0+ with font embedding exception / OFL-1.1), box-filtered to 4x8 and
mirrored left-to-right like the glyphs in the film.

Usage: python3 tools/gen_kana.py [path/to/unifont.otf]   (needs Pillow)
"""
import sys
from PIL import Image, ImageDraw, ImageFont

font_path = sys.argv[1] if len(sys.argv) > 1 else "/usr/share/fonts/opentype/unifont/unifont.otf"
font = ImageFont.truetype(font_path, 16)
first, last = 0xFF66, 0xFF9D

rows = []
for cp in range(first, last + 1):
    im = Image.new("L", (8, 16), 0)
    ImageDraw.Draw(im).text((0, 0), chr(cp), font=font, fill=255)
    small = im.resize((4, 8), Image.BOX).transpose(Image.FLIP_LEFT_RIGHT)
    glyph = []
    for y in range(8):
        bits = 0
        for x in range(4):
            if small.getpixel((x, y)) > 60:
                bits |= 1 << (3 - x)
        glyph.append(bits)
    rows.append((cp, glyph))

with open("src/kana_glyphs.nim", "w") as out:
    out.write("## Generated by tools/gen_kana.py from GNU Unifont. Do not edit.\n")
    out.write("## 4x8 mirrored half-width katakana; bit 3 is the leftmost pixel.\n\n")
    out.write(f"const\n  KanaFirst* = 0x{first:X}\n  KanaLast* = 0x{last:X}\n")
    out.write(f"  KanaGlyphs*: array[{len(rows)}, array[8, uint8]] = [\n")
    for cp, glyph in rows:
        vals = ", ".join(f"0x{b:X}'u8" for b in glyph)
        out.write(f"    [{vals}], # U+{cp:04X} {chr(cp)}\n")
    out.write("  ]\n")
